"""adiciona unidade de idade aos animais

Revision ID: 1bf619df254e
Revises: c82f0cc37979
Create Date: 2026-09-17 13:37:05.924612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1bf619df254e'
down_revision: Union[str, Sequence[str], None] = 'c82f0cc37979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('unidade_idade', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal', 'unidade_idade')
    # ### end Alembic commands ###
