"""adicionar foto ao perfil

Revision ID: 42d481401bc6
Revises: 1bf619df254e
Create Date: 2026-09-23 18:56:12.025460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '42d481401bc6'
down_revision: Union[str, Sequence[str], None] = '1bf619df254e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ong', sa.Column('foto', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('foto', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'foto')
    op.drop_column('ong', 'foto')
    # ### end Alembic commands ###
